### ISSUE TITLE
Just an FYI about those PKMs...

### ISSUE THREAD

**Issue by applecuckoo** [lfhacks/Virtuos-LeapFrog-game-tools#3]
Hello again! Yes, I'm still lurking :-)

Anyways, I saw your note on decoding PKMs and I wanted to note that [Tacent View](https://github.com/bluescan/tacentview) is able to open them. Mainly wrote this since I wasn't sure if Virtuos used *another* PKM format apart from the one I already knew until you updated the README - From the two LeapFrog games I have, none of them use PKM.

P.S. Thanks for the mention, but I also have to give a huge thanks to the [ResHax folks](https://reshax.com/topic/588-leapfrog-udi-files/) for helping me decode those UDIs.

P.P.S. It might be a good idea to turn on GitHub discussions - I don't want to clog up your issue tracker with these posts!

**Comment by BLiNXthetimesweeperGOD** [comment]
Turned on discussions. I was fine with the issues, but it's good to know there's a better way to handle this stuff.
